version: "3.7"

services:
  appnode:
    container_name: appnode
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run dev
