import Head from 'next/head'
import Cookies from 'cookies'
import { useEffect, useState } from 'react'
import { useUser } from '../hoocks/userContext';

export default function Home({url, user={}, token_ = ''}) {
  
  const [items, setItems] = useState([]);
  const [textName, setTextName] = useState('');
  const [textDescription, setTextDescription] = useState('');
  const [msg, setMsg] = useState('');
  const {updateData, userName, email, id, logOut, token} = useUser();
  useEffect(()=>{
    const getData = async()=>{
      const res = await fetch(`http://${url}/api/items`);
      const _items = await res.json()
      setItems(_items);
    }
    getData();
    if(user!=={}){
      console.log("Atualizando user: " + user.username);
      console.log(token_)
      updateData({
        name: user.username,
        email: user.email,
        id: user.id,
        token: token_,
      });
    }
  },[])
  const handleCreateItem = async()=>{
    setMsg('');
    if(textName=='' || textDescription==''){
      setMsg("*Preencha todos os campos");
      return;
    }
    console.log("clicou em criar item");
    const res = await fetch(`http://${url}/api/items`, {
      method: 'POST',
      body: JSON.stringify({ 
        name: textName,
        description: textDescription
      }),
      headers: { 
        'Content-Type': 'application/json', 
        'token': token,
      },
    })
    const response = await res.json();
    console.log(response);
    if(response.status){
      setMsg(`${textName} criado com sucesso!`);
      setItems([...items, {name: textName, description: textDescription, id: response.id, username: userName}])
    }else{
      setMsg(`${textName} algo deu errado`);
    }
    setTextName('');
    setTextDescription('');
  }
  const handleDeleteItem = async (id, name)=>{
    console.log("clicou em Deletar item");
    const res = await fetch(`http://${url}/api/items`, {
      method: 'DELETE',
      body: JSON.stringify({ 
        id: id,
      }),
      headers: { 'Content-Type': 'application/json' },
    })
    const response = await res.json();
    if(response.status){
      setMsg(`${name} deletado com sucesso!`);
      setItems(items.filter((item)=>{
        return item.id !== id && item;
      }));
    }else{
      setMsg(`${textName} algo deu errado`);
    }
  }
  const handleLogOut = ()=>{
    logOut();
  }
  return (
    <div style={{minHeight:'100vh'}}>
      <div style={{
        backgroundColor: 'aliceblue', 
        display: 'flex', 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        padding: '0 50px',
        alignItems: 'center',
      }}>
        <h1>feadonai.ninja</h1>
        <div style={{display: 'flex', flexDirection: 'row', alignItems: 'center'}}>
          <h1>{userName}</h1>
          <button style={{
            marginLeft: '20px', 
            padding: '0 20px', 
            boxShadow: '0 0 0 0',
            borderWidth: '2px',
            borderColor: '#f71',
            outline: 0,
            backgroundColor: 'aliceblue',
            borderRadius: '20px',
          }} onClick={handleLogOut}>
            <h3>LogOut</h3> 
          </button>
        </div>
      </div>
      <div style={{
        display: 'flex', 
        flexDirection: 'column',  
        padding: '50px',
        backgroundColor: '#f71',
        
      }}>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div style={{
          display:'flex', 
          flexDirection: 'column', 
          alignItems: 'center', 
          justifyContent: 'center',
          padding: '20px',
          alignSelf: 'center',
          width: 'fit-content',
          backgroundColor: 'aliceblue',
          borderRadius: '20px',
        }}>
          <h2>Titulo: </h2>
          <input 
            style={{
              borderRadius: '20px',
              padding: '5px 20px',
              boxShadow: '0 0 0 0',
              borderWidth: '2px',
              borderColor: '#f71',
              outline: 0,
            }}
            typeof="text" 
            placeholder="Nome"
            value={textName}
            onChange={(e)=>setTextName(e.target.value)}
          ></input>
          <h2>Descrição: </h2>
          <input 
            style={{
              borderRadius: '20px',
              padding: '5px 20px',
              boxShadow: '0 0 0 0',
              borderWidth: '2px',
              borderColor: '#f71',
              outline: 0,
            }}
            typeof="text" 
            placeholder="Description"
            value={textDescription}
            onChange={(e)=>setTextDescription(e.target.value)}
          ></input>
          <button 
            onClick={handleCreateItem}
            style={{
              marginTop: '20px', 
              borderRadius: '20px', 
              padding: '10px 20px',
              boxShadow: '0 0 0 0',
              borderWidth: '2px',
              borderColor: '#f71',
              outline: 0,
              backgroundColor: 'aliceblue'
            }}
          >Criar item</button>
          <p style={{color: '#f00', marginTop: '20px', fontSize: '12px', visibility: msg===''&&'hidden'}}>{msg===''?'.':msg}</p>
        </div>
        <div>
          {items.length>0 && items.map((item)=>{
            console.log("banco: " + item.id)
            console.log("meu: " + id)

            return(
              <div style={{display: 'flex', flexDirection: 'column'}}>
                <h1 style={{
                  margin: 0,     
                  position: 'absolute',
                  backgroundColor: item.username===userName?'#f71':'aliceblue',
                  padding: '5px 20px',
                  borderWidth: '2px',
                  borderColor: '#f71',
                  borderTopLeftRadius: '20px',
                  borderTopRightRadius: '20px',
                }}>{item.username}</h1>
                <div key={item.id} style={{
                  margin: '20px 0',
                  backgroundColor: item.username===userName?'#f71':'aliceblue',
                  display: 'flex',
                  flexDirection: 'row',
                  justifyContent: 'space-between',
                  borderRadius: '20px',
                  borderWidth: '2px',
                  borderColor: item.username===userName?'aliceblue':'#f71',
                  borderStyle: item.username===userName?'dotted':'none',
                }}>
                  <div style={{
                    padding: '5px 20px',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'space-around',
                    minHeight: '64x',
                  }}>
                    <h2 style={{margin: '26px 0 5px 0'}}><strong><label>{item.name}</label></strong></h2>
                    <p style={{margin: '0 0 5px 0'}}><label>{item.description}</label></p>
                  </div>
                  <button 
                    onClick={()=>handleDeleteItem(item.id, item.name)}
                    style={{
                      borderRadius: '20px', 
                      padding: '10px 20px',
                      boxShadow: '0 0 0 0',
                      borderWidth: '2px',
                      borderColor: '#f71',
                      outline: 0,
                      backgroundColor: 'aliceblue'
                    }} 
                  >Deletar</button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  console.log("getServerSideProps")
  const {req, res} = context;
  console.log(req.headers.host);
  const url = req.headers.host;
  //const res = await fetch(`http://${url}/api/items`);
  //const data = await res.json()
  //console.log(data);
  const cookies = new Cookies(req, res)
  const token = cookies.get('token')
  console.log("verificando token: " + token)
  if(token){
    console.log("token existente");
    const res = await fetch(`http://${url}/api/users/signIn`, {
      method: 'POST',
      body: JSON.stringify({ 
        token: token,
      }),
      headers: { 'Content-Type': 'application/json' },
    })
    const response = await res.json();
    console.log("resposta: ");
    console.log(response);
    if(response.status){
      cookies.set('token', token, {
        httpOnly: false
      })
      return { props: { url : url, user : response.data, token_: token } }
    }    
  }
  return { 
    redirect: {
      destination: '/signIn',
      permanent: false,
    },
  }
}