import Head from 'next/head'
import { useState } from 'react'

export default function Home({data, url}) {
  
  const [items, setItems] = useState(data);
  const [textName, setTextName] = useState('');
  const [textDescription, setTextDescription] = useState('');
  const [msg, setMsg] = useState('');

  const handleCreateItem = async()=>{
    setMsg('');
    if(textName=='' || textDescription==''){
      setMsg("*Preencha todos os campos");
      return;
    }
    console.log("clicou em criar item");
    const res = await fetch(`http://${url}/api/items`, {
      method: 'POST',
      body: JSON.stringify({ 
        name: textName,
        description: textDescription
      }),
      headers: { 'Content-Type': 'application/json' },
    })
    const response = await res.json();
    console.log(response);
    if(response.status){
      setMsg(`${textName} criado com sucesso!`);
      setItems([...items, {name: textName, description: textDescription, id: response.id}])
    }else{
      setMsg(`${textName} algo deu errado`);
    }
    setTextName('');
    setTextDescription('');
  }
  const handleDeleteItem = async (id, name)=>{
    console.log("clicou em Deletar item");
    const res = await fetch(`http://${url}/api/items`, {
      method: 'DELETE',
      body: JSON.stringify({ 
        id: id,
      }),
      headers: { 'Content-Type': 'application/json' },
    })
    const response = await res.json();
    if(response.status){
      setMsg(`${name} deletado com sucesso!`);
      setItems(items.filter((item)=>{
        return item.id !== id && item;
      }));
    }else{
      setMsg(`${textName} algo deu errado`);
    }
    
  }
  return (
    <div style={{
      display: 'flex', 
      flexDirection: 'column',  
      padding: '50px',
      backgroundColor: '#f71',
    }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 style={{justifySelf: 'center', alignSelf: 'center', marginBottom: '20px'}}>Welcome to Next.js</h1>
      <div style={{
        display:'flex', 
        flexDirection: 'column', 
        alignItems: 'center', 
        justifyContent: 'center',
        padding: '20px',
        alignSelf: 'center',
        width: 'fit-content',
        backgroundColor: 'aliceblue',
        borderRadius: '20px',
      }}>
        <h2>Nome: </h2>
        <input 
          style={{
            borderRadius: '20px',
            padding: '5px 20px',
            boxShadow: '0 0 0 0',
            borderWidth: '2px',
            borderColor: '#f71',
            outline: 0,
          }}
          typeof="text" 
          placeholder="Nome"
          value={textName}
          onChange={(e)=>setTextName(e.target.value)}
        ></input>
        <h2>Descrição: </h2>
        <input 
          style={{
            borderRadius: '20px',
            padding: '5px 20px',
            boxShadow: '0 0 0 0',
            borderWidth: '2px',
            borderColor: '#f71',
            outline: 0,
          }}
          typeof="text" 
          placeholder="Description"
          value={textDescription}
          onChange={(e)=>setTextDescription(e.target.value)}
        ></input>
        <button 
          onClick={handleCreateItem}
          style={{
            marginTop: '20px', 
            borderRadius: '20px', 
            padding: '10px 20px',
            boxShadow: '0 0 0 0',
            borderWidth: '2px',
            borderColor: '#f71',
            outline: 0,
            backgroundColor: 'aliceblue'
          }}
        >Criar item</button>
        <p style={{color: '#f00', marginTop: '20px', fontSize: '12px', visibility: msg===''&&'hidden'}}>{msg===''?'.':msg}</p>
      </div>
      <div>
        {items.length>0 && items.map((item)=>{
          return(
            <div key={item.id} style={{
              margin: '20px 0',
              backgroundColor: 'aliceblue',
              display: 'flex',
              flexDirection: 'row',
              justifyContent: 'space-between',
              borderRadius: '20px',
            }}>
              <div style={{
                padding: '5px 20px',
              }}>
                <h2><strong>Nome: </strong><label>{item.name}</label></h2>
                <p><strong>Descrição: </strong><label>{item.description}</label></p>
              </div>
              <button 
                onClick={()=>handleDeleteItem(item.id, item.name)}
                style={{
                  borderRadius: '20px', 
                  padding: '10px 20px',
                  boxShadow: '0 0 0 0',
                  borderWidth: '2px',
                  borderColor: '#f71',
                  outline: 0,
                  backgroundColor: 'aliceblue'
                }} 
              >Deletar</button>
            </div>
          );
        })}
      </div>
    </div>
  )
}

export async function getServerSideProps(context) {
  
  const {req} = context;
  console.log(req.headers.host);
  const url = req.headers.host;
  const res = await fetch(`http://${url}/api/items`);
  const data = await res.json()
  console.log(data);
  return { props: { data, url } }
}