import { useState } from "react";
import { useUser } from "../hoocks/userContext";
import Router from 'next/router'
import Head from 'next/head'
import Link from 'next/link'

const signIn = ({url})=>{
  const [text, setText] = useState('');
  const [msgError, setMsgError] = useState("");
  const [pass, setPass] = useState('');
  const {login} = useUser();

  const handleSubmit = async(event)=>{
    console.log("Clicado em Login");
    event.preventDefault();
    setMsgError('');
    if(text==='' || pass===''){
      setMsgError('*Preencha todos os campos');
      return;
    }
    console.log("logando...");
    const response = await login({
      text: text,
      pass: pass,
      url: url,
    });
    console.log(response);
    if(response.status){
      Router.push('/');
    }else{
      setMsgError(`ERRO: ${response.msg}`);
    }
    setText('');
    setPass('');
  }
  return(
    <div style={{
      display: 'flex', 
      flexDirection: 'column', 
      alignItems: 'center', 
      justifyContent: 'center',
      padding: '50px',
      backgroundColor: '#f71',
      height: '100vh',
    }}>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={handleSubmit} style={{
        alignSelf: 'center',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '0px 50px',
        backgroundColor: 'aliceblue',
        borderRadius: '20px',
        width: '40vw',
      }}>
        <div style={{
          alignItems: 'flex-start',
          display: 'flex',
          flexDirection: 'column',
        }}>
          <h1 style={{alignSelf: 'center'}}>Login</h1>
          <h3 style={{marginBottom: '5px'}}>E-mail ou Username:</h3>
          <input 
            type="text" 
            placeholder="Nome ou Email"
            value={text}
            onChange={(e)=>setText(e.target.value)} 
            style={{
              width: '100%',
              borderRadius: '20px',
              padding: '5px 20px',
              boxShadow: '0 0 0 0',
              borderWidth: '2px',
              borderColor: '#f71',
              outline: 0,
            }}
          />
          <h3 style={{marginBottom: '5px'}}>Senha:</h3>
          <input 
            type="password" 
            placeholder="Senha" 
            value={pass}
            onChange={(e)=>setPass(e.target.value)} 
            style={{
              width: '100%',
              borderRadius: '20px',
              padding: '5px 20px',
              boxShadow: '0 0 0 0',
              borderWidth: '2px',
              borderColor: '#f71',
              outline: 0,
            }}
          /><br/>
        </div>
        <div style={{display: 'flex', flexDirection: 'column', alignItems: 'center'}}>
          <input 
            type="submit" 
            value="Login"
            style={{
              marginTop: '20px', 
              borderRadius: '20px', 
              padding: '10px 20px',
              boxShadow: '0 0 0 0',
              borderWidth: '2px',
              borderColor: '#f71',
              outline: 0,
              backgroundColor: 'aliceblue',   
              width: '100%',       
            }}
          />
          <p style={{cursor: 'default'}}>Não tem uma conta? Clique  <Link href="/signUp"><strong><a style={{cursor: 'pointer'}}>aqui</a></strong></Link> para se registrar</p>
          <p style={{color: '#f00', textAlign: 'center', margin: '5px 0px', fontSize: '12px', visibility: msgError===''&&'hidden'}}>{msgError===''?'.':msgError}</p> 
        </div>
      </form>
    </div>
  );
}
/*
<label>Anexo</label>
<input type="file" id="anexo" name="anexo" />
*/
export default signIn;

export async function getServerSideProps(context) {
  
  const {req} = context;
  console.log(req.headers.host);
  const url = req.headers.host;
  return { props: { url } }
}